### ISSUE TITLE
[Question] SignalR

### ISSUE THREAD

**Issue by GiannhsR** [IEvangelist/learning-blazor#46]
Hello, @IEvangelist 

I have been studying your SignalR implementation and I find it kind of confusing to get my head around your way of actually implementing the SharedHubConnections, especially the registered IDisposable client methods (see SubscribeToUserLoggedIn).

Is there a pattern/best practice that you are following for the declaration of the client methods?
Are they available throughout the application?

I am aware that the repo is supplementary to your book but I was wondering if you could provide some information before the release date.

Best regards

**Comment by IEvangelist** [comment]
Hi @GiannhsR,

Thank you so much for your interest in this project and specifically the approach that I'm taking with regard to SignalR. The `SharedHubConnection` is split into various `partial` implementations. This is intentional, and considered idiomatic C#. I'm just applying the usage of `partial class` to the shared hub connection. Throughout the client app, I only want a single hub connection at any given time. The idea is that various components might be interested in some of the same server events. They're free to register for them. The `Subscribe*` methods are just a means to expose named accessors to the underlying `_hubConnection`. Does that make sense?

The framework-provided `HubConnection` is powerful, but its API surface area is a bit too generic. The  `SharedHubConnection` exposes domain specific methods, which are then consumed by any number of components in a shared manner.

**Comment by GiannhsR** [comment]
> Throughout the client app, I only want a single hub connection at any given time. The idea is that various components might be interested in some of the same server events. 

So, that is the reason the SharedHubConnection is registered as a Singleton. Wouldn't that allow someone to inject the SharedHubConnection and do `StartAsync()` leading to multiple open connections? How are you handling that?

> The `Subscribe* `methods are just a means to expose named accessors to the underlying `_hubConnection`

From my understaning, when the client receives a method with the name `HubServerEventNames.UserLoggedIn` ,
`OnUserLoggedInAsync` will run but I can't find how you have managed to wire the HubConnection with that method.
If pushing that method into `Stack<IDisposable> _subscriptions` is the actual wiring then that seems some kind of magic.

Another question, in `SharedHubConnection.cs` when does `DisposeAsync()` run?
After the connection is stopped? 
When the client is disoconnected?
When the browser is closed?

**Comment by IEvangelist** [comment]
> So, that is the reason the SharedHubConnection is registered as a Singleton. Wouldn't that allow someone to inject the SharedHubConnection and do `StartAsync()` leading to multiple open connections? How are you handling that?

There is a lock to ensure that it only one consumer can start the connection.

See: https://github.com/IEvangelist/learning-blazor/blob/main/src/Web.Client/RealTime/SharedHubConnection.Commands.cs#L10

The `_lock` instance is initialized here:

https://github.com/IEvangelist/learning-blazor/blob/main/src/Web.Client/RealTime/SharedHubConnection.cs#L13

> From my understanding, when the client receives a method with the name `HubServerEventNames.UserLoggedIn` , `OnUserLoggedInAsync` will run but I can't find how you have managed to wire the `HubConnection` with that method.

You are correct, that will run when the named method is received. This uses the underlying `_hubConnection` to register to the event, using the [`.On` API](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnection.on?view=aspnetcore-6.0).

See: https://github.com/IEvangelist/learning-blazor/blob/main/src/Web.Client/RealTime/SharedHubConnection.Chat.cs#L31-L35

> Another question, in `SharedHubConnection.cs` when does `DisposeAsync()` run? After the connection is stopped? When the client is disconnected? When the browser is closed?

When the browser (or tab) is closed. It's clean up, but it's not explicitly required since everything in the tab is being torn down.

I detail all of this, the pattern, the architecture, the separation of domain specific `partial class's` in my book.

**Comment by IEvangelist** [comment]
I'm going to close this issue, but feel free to continue asking questions if you need more information.
